/*
  # FPL AI Assistant Database Schema

  1. New Tables
    - `players`
      - Caches FPL player data from the API
      - Stores current stats, form, pricing, and performance metrics
      - Updated periodically from FPL API
    
    - `teams`
      - Caches Premier League team data
      - Stores strength ratings and current standings
      - Updated periodically from FPL API
    
    - `fixtures`
      - Caches fixture schedule and results
      - Stores difficulty ratings and match stats
      - Updated periodically from FPL API
    
    - `gameweeks`
      - Caches gameweek information
      - Stores deadlines and average scores
      - Updated periodically from FPL API
    
    - `player_predictions`
      - Stores ML model predictions for players
      - Includes expected points and risk assessments
      - Generated by prediction service
    
    - `team_analyses`
      - Stores user team analysis results
      - Includes transfer suggestions and captain picks
      - Generated from OCR or manual team input
    
    - `cache_metadata`
      - Tracks when cached data was last updated
      - Used to determine when to refresh from FPL API

  2. Security
    - Enable RLS on all tables
    - Public read access for reference data (players, teams, fixtures, gameweeks)
    - Authenticated users can read their own analyses and predictions
*/

-- Players table
CREATE TABLE IF NOT EXISTS players (
  id bigint PRIMARY KEY,
  web_name text NOT NULL,
  first_name text NOT NULL,
  second_name text NOT NULL,
  team_id bigint NOT NULL,
  team_code bigint NOT NULL,
  element_type int NOT NULL,
  status text NOT NULL DEFAULT 'a',
  chance_of_playing_next_round int,
  chance_of_playing_this_round int,
  now_cost int NOT NULL,
  cost_change_start int DEFAULT 0,
  cost_change_event int DEFAULT 0,
  form numeric(10,2) DEFAULT 0,
  points_per_game numeric(10,2) DEFAULT 0,
  total_points int DEFAULT 0,
  event_points int DEFAULT 0,
  minutes int DEFAULT 0,
  goals_scored int DEFAULT 0,
  assists int DEFAULT 0,
  clean_sheets int DEFAULT 0,
  goals_conceded int DEFAULT 0,
  own_goals int DEFAULT 0,
  penalties_saved int DEFAULT 0,
  penalties_missed int DEFAULT 0,
  yellow_cards int DEFAULT 0,
  red_cards int DEFAULT 0,
  saves int DEFAULT 0,
  bonus int DEFAULT 0,
  bps int DEFAULT 0,
  influence numeric(10,2) DEFAULT 0,
  creativity numeric(10,2) DEFAULT 0,
  threat numeric(10,2) DEFAULT 0,
  ict_index numeric(10,2) DEFAULT 0,
  selected_by_percent numeric(10,2) DEFAULT 0,
  transfers_in bigint DEFAULT 0,
  transfers_out bigint DEFAULT 0,
  transfers_in_event bigint DEFAULT 0,
  transfers_out_event bigint DEFAULT 0,
  expected_goals numeric(10,2),
  expected_assists numeric(10,2),
  expected_goal_involvements numeric(10,2),
  expected_goals_conceded numeric(10,2),
  updated_at timestamptz DEFAULT now()
);

-- Teams table
CREATE TABLE IF NOT EXISTS teams (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  short_name text NOT NULL,
  code bigint NOT NULL,
  strength int DEFAULT 0,
  strength_overall_home int DEFAULT 0,
  strength_overall_away int DEFAULT 0,
  strength_attack_home int DEFAULT 0,
  strength_attack_away int DEFAULT 0,
  strength_defence_home int DEFAULT 0,
  strength_defence_away int DEFAULT 0,
  played int DEFAULT 0,
  win int DEFAULT 0,
  draw int DEFAULT 0,
  loss int DEFAULT 0,
  points int DEFAULT 0,
  position int DEFAULT 0,
  form numeric(10,2),
  updated_at timestamptz DEFAULT now()
);

-- Fixtures table
CREATE TABLE IF NOT EXISTS fixtures (
  id bigint PRIMARY KEY,
  event int,
  team_h bigint NOT NULL,
  team_a bigint NOT NULL,
  team_h_score int,
  team_a_score int,
  team_h_difficulty int DEFAULT 0,
  team_a_difficulty int DEFAULT 0,
  kickoff_time timestamptz,
  started boolean DEFAULT false,
  finished boolean DEFAULT false,
  finished_provisional boolean DEFAULT false,
  stats jsonb,
  updated_at timestamptz DEFAULT now()
);

-- Gameweeks table
CREATE TABLE IF NOT EXISTS gameweeks (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  deadline_time timestamptz NOT NULL,
  is_previous boolean DEFAULT false,
  is_current boolean DEFAULT false,
  is_next boolean DEFAULT false,
  finished boolean DEFAULT false,
  average_entry_score int,
  highest_score int,
  highest_scoring_entry bigint,
  chip_plays jsonb,
  updated_at timestamptz DEFAULT now()
);

-- Player predictions table
CREATE TABLE IF NOT EXISTS player_predictions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id bigint NOT NULL,
  gameweek_id bigint NOT NULL,
  expected_points numeric(10,2) NOT NULL,
  expected_points_floor numeric(10,2) NOT NULL,
  expected_points_ceiling numeric(10,2) NOT NULL,
  start_probability numeric(3,2) NOT NULL,
  expected_minutes numeric(10,2) NOT NULL,
  rotation_risk numeric(3,2) NOT NULL,
  injury_risk numeric(3,2) NOT NULL,
  confidence_score numeric(3,2) NOT NULL,
  key_factors jsonb DEFAULT '[]',
  fixture_difficulty int,
  opponent text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(player_id, gameweek_id)
);

-- Team analyses table
CREATE TABLE IF NOT EXISTS team_analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  team_value numeric(10,1) NOT NULL,
  free_transfers int DEFAULT 1,
  bank numeric(10,1) DEFAULT 0,
  players jsonb NOT NULL,
  captain_id bigint,
  vice_captain_id bigint,
  predicted_gameweek_points numeric(10,2) NOT NULL,
  predicted_bench_points numeric(10,2) NOT NULL,
  transfer_suggestions jsonb DEFAULT '[]',
  captain_suggestion jsonb,
  vice_captain_suggestion jsonb,
  bench_order jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now()
);

-- Cache metadata table
CREATE TABLE IF NOT EXISTS cache_metadata (
  cache_key text PRIMARY KEY,
  last_updated timestamptz DEFAULT now(),
  expires_at timestamptz,
  data_type text NOT NULL
);

-- Enable Row Level Security
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE fixtures ENABLE ROW LEVEL SECURITY;
ALTER TABLE gameweeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE cache_metadata ENABLE ROW LEVEL SECURITY;

-- RLS Policies for public reference data
CREATE POLICY "Anyone can view players"
  ON players FOR SELECT
  USING (true);

CREATE POLICY "Anyone can view teams"
  ON teams FOR SELECT
  USING (true);

CREATE POLICY "Anyone can view fixtures"
  ON fixtures FOR SELECT
  USING (true);

CREATE POLICY "Anyone can view gameweeks"
  ON gameweeks FOR SELECT
  USING (true);

CREATE POLICY "Anyone can view predictions"
  ON player_predictions FOR SELECT
  USING (true);

CREATE POLICY "Anyone can view cache metadata"
  ON cache_metadata FOR SELECT
  USING (true);

-- RLS Policies for team analyses
CREATE POLICY "Users can view own team analyses"
  ON team_analyses FOR SELECT
  USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Anyone can insert team analyses"
  ON team_analyses FOR INSERT
  WITH CHECK (true);

-- Service role policies for data updates
CREATE POLICY "Service can update players"
  ON players FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service can update teams"
  ON teams FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service can update fixtures"
  ON fixtures FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service can update gameweeks"
  ON gameweeks FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service can update predictions"
  ON player_predictions FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service can update cache metadata"
  ON cache_metadata FOR ALL
  USING (true)
  WITH CHECK (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_players_team ON players(team_id);
CREATE INDEX IF NOT EXISTS idx_players_element_type ON players(element_type);
CREATE INDEX IF NOT EXISTS idx_players_total_points ON players(total_points DESC);
CREATE INDEX IF NOT EXISTS idx_players_now_cost ON players(now_cost);
CREATE INDEX IF NOT EXISTS idx_fixtures_event ON fixtures(event);
CREATE INDEX IF NOT EXISTS idx_fixtures_teams ON fixtures(team_h, team_a);
CREATE INDEX IF NOT EXISTS idx_fixtures_kickoff ON fixtures(kickoff_time);
CREATE INDEX IF NOT EXISTS idx_predictions_player ON player_predictions(player_id);
CREATE INDEX IF NOT EXISTS idx_predictions_gameweek ON player_predictions(gameweek_id);
CREATE INDEX IF NOT EXISTS idx_analyses_user ON team_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_created ON team_analyses(created_at DESC);
